### ISSUE TITLE
Number of links in a question doesn't update after link has been added

### ISSUE THREAD

**Issue by neeilan** [neeilan/QuizApp#1]
Also, having a "Save" button or something similar on the modal instead of the x (which often means cancel changes) to save changes would be nice.

**Comment by mikey213** [comment]
I removed the design "# of files/links added/selected". It will only get updated once you save the entire question. For your other suggestion, having a Save button would be lying to the user as it is not saving anything when you close the modal.

**Comment by neeilan** [comment]
I shall consider this resolved.
